config/routes.rb
Purchasing::Application.routes.draw do
  resources :vendors

  resources :bid_types

  get "home/index"

  resources :contacts

  resources :solicitations
  
  root :to => "home#index"

end

app/models/solicitation.rb
class Solicitation < ActiveRecord::Base
  
  belongs_to :bid_type
  belongs_to :contact
  
  
   validates :bid_description,  :presence => true
   validates :bid_number,  :presence => true

end
  

app/controllers/solicitations_controller.rb
class SolicitationsController < ApplicationController
  # GET /solicitations
  # GET /solicitations.xml
  def index
    @solicitations = Solicitation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @solicitations }
    end
  end

  # GET /solicitations/1
  # GET /solicitations/1.xml
  def show
    @solicitation = Solicitation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @solicitation }
    end
  end

  # GET /solicitations/new
  # GET /solicitations/new.xml
  def new
    @solicitation = Solicitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @solicitation }
    end
  end

  # GET /solicitations/1/edit
  def edit
    @solicitation = Solicitation.find(params[:id])
  end

  # POST /solicitations
  # POST /solicitations.xml
  def create
    @solicitation = Solicitation.new(params[:solicitation])

    respond_to do |format|
      if @solicitation.save
        format.html { redirect_to(@solicitation, :notice => 'Solicitation was successfully created.') }
        format.xml  { render :xml => @solicitation, :status => :created, :location => @solicitation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @solicitation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /solicitations/1
  # PUT /solicitations/1.xml
  def update
    @solicitation = Solicitation.find(params[:id])

    respond_to do |format|
      if @solicitation.update_attributes(params[:solicitation])
        format.html { redirect_to(@solicitation, :notice => 'Solicitation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @solicitation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /solicitations/1
  # DELETE /solicitations/1.xml
  def destroy
    @solicitation = Solicitation.find(params[:id])
    @solicitation.destroy

    respond_to do |format|
      format.html { redirect_to(solicitations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/solicitations_helper.rb
module SolicitationsHelper
end

app/views/solicitations/_form.html.erb
<%= form_for(@solicitation) do |f| %>
  <% if @solicitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solicitation.errors.count, "error") %> prohibited this solicitation from being saved:</h2>

      <ul>
      <% @solicitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bid_type %><br />
	<%= select("solicitation", "bid_type_id", BidType.all.collect {|p| [ p.description, p.id ] })%>
	 
  </div>
  <div class="field">
    <%= f.label :bid_number %><br />
    <%= f.text_area :bid_number %>
  </div>
  <div class="field">
    <%= f.label :bid_description %><br />
    <%= f.text_area :bid_description %>
  </div>
  <div class="field">
    <%= f.label :open_date %><br />
    <%= f.date_select :open_date %>
  </div>
  <div class="field">
    <%= f.label :closed_date %><br />
    <%= f.date_select :closed_date %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br />
	<%= select("solicitation", "contact_id", Contact.all.collect {|p| [ p.name, p.id ] })%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solicitations/edit.html.erb
<h1>Editing solicitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @solicitation %> |
<%= link_to 'Back', solicitations_path %>

app/views/solicitations/index.html.erb
<h1>Listing solicitations</h1>

<table>
  <tr>
    <th>Bid type</th>
	<th>Bid Number</th>
    <th>Bid description</th>
    <th>Open date</th>
    <th>Closed date</th>
    <th>Contact</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @solicitations.each do |solicitation| %>
  <tr>
    <td><%= solicitation.bid_type.abbreviation %></td>
 	<td><%= solicitation.bid_number %></td>
    <td><%= solicitation.bid_description %></td>
    <td><%= solicitation.open_date %></td>
    <td><%= solicitation.closed_date %></td>
    <td><%= solicitation.contact.name %></td>
    <td><%= link_to 'Show', solicitation %></td>
    <td><%= link_to 'Edit', edit_solicitation_path(solicitation) %></td>
    <td><%= link_to 'Destroy', solicitation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Solicitation', new_solicitation_path %>

app/views/solicitations/new.html.erb
<h1>New solicitation</h1>

<%= render 'form' %>

<%= link_to 'Back', solicitations_path %>

app/views/solicitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bid type:</b>
  <%= @solicitation.bid_type.abbreviation %>
</p>

<p>
  <b>Bid Number:</b>
  <%= @solicitation.bid_number %>
</p>

<p>
  <b>Bid description:</b>
  <%= @solicitation.bid_description %>
</p>

<p>
  <b>Open date:</b>
  <%= @solicitation.open_date %>
</p>

<p>
  <b>Closed date:</b>
  <%= @solicitation.closed_date %>
</p>

<p>
  <b>Contact:</b>
  <%= @solicitation.contact.name %>
</p>


<%= link_to 'Edit', edit_solicitation_path(@solicitation) %> |
<%= link_to 'Back', solicitations_path %>