config/routes.rb
Purchasing::Application.routes.draw do
  resources :vendors

  resources :bid_types

  get "home/index"

  resources :contacts

  resources :solicitations
  
  root :to => "home#index"

end

app/controllers/bid_types_controller.rb
class BidTypesController < ApplicationController
  # GET /bid_types
  # GET /bid_types.xml
  def index
    @bid_types = BidType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bid_types }
    end
  end

  # GET /bid_types/1
  # GET /bid_types/1.xml
  def show
    @bid_type = BidType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bid_type }
    end
  end

  # GET /bid_types/new
  # GET /bid_types/new.xml
  def new
    @bid_type = BidType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bid_type }
    end
  end

  # GET /bid_types/1/edit
  def edit
    @bid_type = BidType.find(params[:id])
  end

  # POST /bid_types
  # POST /bid_types.xml
  def create
    @bid_type = BidType.new(params[:bid_type])

    respond_to do |format|
      if @bid_type.save
        format.html { redirect_to(@bid_type, :notice => 'Bid type was successfully created.') }
        format.xml  { render :xml => @bid_type, :status => :created, :location => @bid_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bid_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bid_types/1
  # PUT /bid_types/1.xml
  def update
    @bid_type = BidType.find(params[:id])

    respond_to do |format|
      if @bid_type.update_attributes(params[:bid_type])
        format.html { redirect_to(@bid_type, :notice => 'Bid type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bid_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bid_types/1
  # DELETE /bid_types/1.xml
  def destroy
    @bid_type = BidType.find(params[:id])
    @bid_type.destroy

    respond_to do |format|
      format.html { redirect_to(bid_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bid_types_helper.rb
module BidTypesHelper
end

app/views/bid_types/_form.html.erb
<%= form_for(@bid_type) do |f| %>
  <% if @bid_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid_type.errors.count, "error") %> prohibited this bid_type from being saved:</h2>

      <ul>
      <% @bid_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bid_types/edit.html.erb
<h1>Editing bid_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid_type %> |
<%= link_to 'Back', bid_types_path %>

app/views/bid_types/index.html.erb
<h1>Listing bid_types</h1>

<table>
  <tr>
    <th>Abbreviation</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bid_types.each do |bid_type| %>
  <tr>
    <td><%= bid_type.abbreviation %></td>
    <td><%= bid_type.description %></td>
    <td><%= link_to 'Show', bid_type %></td>
    <td><%= link_to 'Edit', edit_bid_type_path(bid_type) %></td>
    <td><%= link_to 'Destroy', bid_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bid type', new_bid_type_path %>

app/views/bid_types/new.html.erb
<h1>New bid_type</h1>

<%= render 'form' %>

<%= link_to 'Back', bid_types_path %>

app/views/bid_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Abbreviation:</b>
  <%= @bid_type.abbreviation %>
</p>

<p>
  <b>Description:</b>
  <%= @bid_type.description %>
</p>


<%= link_to 'Edit', edit_bid_type_path(@bid_type) %> |
<%= link_to 'Back', bid_types_path %>